note

	description: "This file has been generated by WrapC. Do not edit. Changes will be lost!"

	generator: "Eiffel Wrapper Generator"
-- functions wrapper
class EWG_EWIRINGPI_CALLBACK_C_GLUE_CODE_FUNCTIONS_API


feature -- Access

	set_void_void_anonymous_callback_object (a_class: POINTER) 
		do
			c_set_void_void_anonymous_callback_object (a_class)
		ensure
			instance_free: class
		end

	release_void_void_anonymous_callback_object
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				release_void_void_anonymous_callback_object ();
			]"
		end

	get_void_void_anonymous_callback_stub_1: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_void_void_anonymous_callback_stub_1 ();
			]"
		end

	get_void_void_anonymous_callback_stub_2: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_void_void_anonymous_callback_stub_2 ();
			]"
		end

	get_void_void_anonymous_callback_stub_3: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_void_void_anonymous_callback_stub_3 ();
			]"
		end

	set_void_void_anonymous_callback_entry_1 (a_feature: POINTER) 
		do
			c_set_void_void_anonymous_callback_entry_1 (a_feature)
		ensure
			instance_free: class
		end

	set_void_void_anonymous_callback_entry_2 (a_feature: POINTER) 
		do
			c_set_void_void_anonymous_callback_entry_2 (a_feature)
		ensure
			instance_free: class
		end

	set_void_void_anonymous_callback_entry_3 (a_feature: POINTER) 
		do
			c_set_void_void_anonymous_callback_entry_3 (a_feature)
		ensure
			instance_free: class
		end

	call_void_void_anonymous_callback (a_function: POINTER) 
		do
			c_call_void_void_anonymous_callback (a_function)
		ensure
			instance_free: class
		end

	set_voidp_voidp_anonymous_callback_object (a_class: POINTER) 
		do
			c_set_voidp_voidp_anonymous_callback_object (a_class)
		ensure
			instance_free: class
		end

	release_voidp_voidp_anonymous_callback_object
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				release_voidp_voidp_anonymous_callback_object ();
			]"
		end

	get_voidp_voidp_anonymous_callback_stub_1: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_voidp_voidp_anonymous_callback_stub_1 ();
			]"
		end

	get_voidp_voidp_anonymous_callback_stub_2: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_voidp_voidp_anonymous_callback_stub_2 ();
			]"
		end

	get_voidp_voidp_anonymous_callback_stub_3: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_voidp_voidp_anonymous_callback_stub_3 ();
			]"
		end

	set_voidp_voidp_anonymous_callback_entry_1 (a_feature: POINTER) 
		do
			c_set_voidp_voidp_anonymous_callback_entry_1 (a_feature)
		ensure
			instance_free: class
		end

	set_voidp_voidp_anonymous_callback_entry_2 (a_feature: POINTER) 
		do
			c_set_voidp_voidp_anonymous_callback_entry_2 (a_feature)
		ensure
			instance_free: class
		end

	set_voidp_voidp_anonymous_callback_entry_3 (a_feature: POINTER) 
		do
			c_set_voidp_voidp_anonymous_callback_entry_3 (a_feature)
		ensure
			instance_free: class
		end

	call_voidp_voidp_anonymous_callback (a_function: POINTER; anonymous_2: POINTER): POINTER 
		do
			Result := c_call_voidp_voidp_anonymous_callback (a_function, anonymous_2)
		ensure
			instance_free: class
		end

	set_void_structwiringpinodestructp_int_int_anonymous_callback_1_object (a_class: POINTER) 
		do
			c_set_void_structwiringpinodestructp_int_int_anonymous_callback_1_object (a_class)
		ensure
			instance_free: class
		end

	release_void_structwiringpinodestructp_int_int_anonymous_callback_1_object
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				release_void_structwiringpinodestructp_int_int_anonymous_callback_1_object ();
			]"
		end

	get_void_structwiringpinodestructp_int_int_anonymous_callback_1_stub_1: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_void_structwiringpinodestructp_int_int_anonymous_callback_1_stub_1 ();
			]"
		end

	get_void_structwiringpinodestructp_int_int_anonymous_callback_1_stub_2: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_void_structwiringpinodestructp_int_int_anonymous_callback_1_stub_2 ();
			]"
		end

	get_void_structwiringpinodestructp_int_int_anonymous_callback_1_stub_3: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_void_structwiringpinodestructp_int_int_anonymous_callback_1_stub_3 ();
			]"
		end

	set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_1 (a_feature: POINTER) 
		do
			c_set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_1 (a_feature)
		ensure
			instance_free: class
		end

	set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_2 (a_feature: POINTER) 
		do
			c_set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_2 (a_feature)
		ensure
			instance_free: class
		end

	set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_3 (a_feature: POINTER) 
		do
			c_set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_3 (a_feature)
		ensure
			instance_free: class
		end

	call_void_structwiringpinodestructp_int_int_anonymous_callback_1 (a_function: POINTER; node: WIRING_PI_NODE_STRUCT_STRUCT_API; pin: INTEGER; mode: INTEGER) 
		do
			c_call_void_structwiringpinodestructp_int_int_anonymous_callback_1 (a_function, node.item, pin, mode)
		ensure
			instance_free: class
		end

	set_int_structwiringpinodestructp_int_anonymous_callback_object (a_class: POINTER) 
		do
			c_set_int_structwiringpinodestructp_int_anonymous_callback_object (a_class)
		ensure
			instance_free: class
		end

	release_int_structwiringpinodestructp_int_anonymous_callback_object
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				release_int_structwiringpinodestructp_int_anonymous_callback_object ();
			]"
		end

	get_int_structwiringpinodestructp_int_anonymous_callback_stub_1: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_int_structwiringpinodestructp_int_anonymous_callback_stub_1 ();
			]"
		end

	get_int_structwiringpinodestructp_int_anonymous_callback_stub_2: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_int_structwiringpinodestructp_int_anonymous_callback_stub_2 ();
			]"
		end

	get_int_structwiringpinodestructp_int_anonymous_callback_stub_3: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_int_structwiringpinodestructp_int_anonymous_callback_stub_3 ();
			]"
		end

	set_int_structwiringpinodestructp_int_anonymous_callback_entry_1 (a_feature: POINTER) 
		do
			c_set_int_structwiringpinodestructp_int_anonymous_callback_entry_1 (a_feature)
		ensure
			instance_free: class
		end

	set_int_structwiringpinodestructp_int_anonymous_callback_entry_2 (a_feature: POINTER) 
		do
			c_set_int_structwiringpinodestructp_int_anonymous_callback_entry_2 (a_feature)
		ensure
			instance_free: class
		end

	set_int_structwiringpinodestructp_int_anonymous_callback_entry_3 (a_feature: POINTER) 
		do
			c_set_int_structwiringpinodestructp_int_anonymous_callback_entry_3 (a_feature)
		ensure
			instance_free: class
		end

	call_int_structwiringpinodestructp_int_anonymous_callback (a_function: POINTER; node: WIRING_PI_NODE_STRUCT_STRUCT_API; pin: INTEGER): INTEGER 
		do
			Result := c_call_int_structwiringpinodestructp_int_anonymous_callback (a_function, node.item, pin)
		ensure
			instance_free: class
		end

	set_void_structwiringpinodestructp_int_int_anonymous_callback_object (a_class: POINTER) 
		do
			c_set_void_structwiringpinodestructp_int_int_anonymous_callback_object (a_class)
		ensure
			instance_free: class
		end

	release_void_structwiringpinodestructp_int_int_anonymous_callback_object
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				release_void_structwiringpinodestructp_int_int_anonymous_callback_object ();
			]"
		end

	get_void_structwiringpinodestructp_int_int_anonymous_callback_stub_1: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_void_structwiringpinodestructp_int_int_anonymous_callback_stub_1 ();
			]"
		end

	get_void_structwiringpinodestructp_int_int_anonymous_callback_stub_2: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_void_structwiringpinodestructp_int_int_anonymous_callback_stub_2 ();
			]"
		end

	get_void_structwiringpinodestructp_int_int_anonymous_callback_stub_3: POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return get_void_structwiringpinodestructp_int_int_anonymous_callback_stub_3 ();
			]"
		end

	set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_1 (a_feature: POINTER) 
		do
			c_set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_1 (a_feature)
		ensure
			instance_free: class
		end

	set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_2 (a_feature: POINTER) 
		do
			c_set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_2 (a_feature)
		ensure
			instance_free: class
		end

	set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_3 (a_feature: POINTER) 
		do
			c_set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_3 (a_feature)
		ensure
			instance_free: class
		end

	call_void_structwiringpinodestructp_int_int_anonymous_callback (a_function: POINTER; node: WIRING_PI_NODE_STRUCT_STRUCT_API; pin: INTEGER; value: INTEGER) 
		do
			c_call_void_structwiringpinodestructp_int_int_anonymous_callback (a_function, node.item, pin, value)
		ensure
			instance_free: class
		end

feature -- Externals

	c_set_void_void_anonymous_callback_object (a_class: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_void_anonymous_callback_object ((void*)$a_class);
			]"
		end

	c_set_void_void_anonymous_callback_entry_1 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_void_anonymous_callback_entry_1 ((void*)$a_feature);
			]"
		end

	c_set_void_void_anonymous_callback_entry_2 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_void_anonymous_callback_entry_2 ((void*)$a_feature);
			]"
		end

	c_set_void_void_anonymous_callback_entry_3 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_void_anonymous_callback_entry_3 ((void*)$a_feature);
			]"
		end

	c_call_void_void_anonymous_callback (a_function: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				call_void_void_anonymous_callback ((void*)$a_function);
			]"
		end

	c_set_voidp_voidp_anonymous_callback_object (a_class: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_voidp_voidp_anonymous_callback_object ((void*)$a_class);
			]"
		end

	c_set_voidp_voidp_anonymous_callback_entry_1 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_voidp_voidp_anonymous_callback_entry_1 ((void*)$a_feature);
			]"
		end

	c_set_voidp_voidp_anonymous_callback_entry_2 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_voidp_voidp_anonymous_callback_entry_2 ((void*)$a_feature);
			]"
		end

	c_set_voidp_voidp_anonymous_callback_entry_3 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_voidp_voidp_anonymous_callback_entry_3 ((void*)$a_feature);
			]"
		end

	c_call_voidp_voidp_anonymous_callback (a_function: POINTER; anonymous_1: POINTER): POINTER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return call_voidp_voidp_anonymous_callback ((void*)$a_function, (void*)$anonymous_1);
			]"
		end

	c_set_void_structwiringpinodestructp_int_int_anonymous_callback_1_object (a_class: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_structwiringpinodestructp_int_int_anonymous_callback_1_object ((void*)$a_class);
			]"
		end

	c_set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_1 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_1 ((void*)$a_feature);
			]"
		end

	c_set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_2 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_2 ((void*)$a_feature);
			]"
		end

	c_set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_3 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_structwiringpinodestructp_int_int_anonymous_callback_1_entry_3 ((void*)$a_feature);
			]"
		end

	c_call_void_structwiringpinodestructp_int_int_anonymous_callback_1 (a_function: POINTER; node: POINTER; pin: INTEGER; mode: INTEGER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				call_void_structwiringpinodestructp_int_int_anonymous_callback_1 ((void*)$a_function, (struct wiringPiNodeStruct*)$node, (int)$pin, (int)$mode);
			]"
		end

	c_set_int_structwiringpinodestructp_int_anonymous_callback_object (a_class: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_int_structwiringpinodestructp_int_anonymous_callback_object ((void*)$a_class);
			]"
		end

	c_set_int_structwiringpinodestructp_int_anonymous_callback_entry_1 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_int_structwiringpinodestructp_int_anonymous_callback_entry_1 ((void*)$a_feature);
			]"
		end

	c_set_int_structwiringpinodestructp_int_anonymous_callback_entry_2 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_int_structwiringpinodestructp_int_anonymous_callback_entry_2 ((void*)$a_feature);
			]"
		end

	c_set_int_structwiringpinodestructp_int_anonymous_callback_entry_3 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_int_structwiringpinodestructp_int_anonymous_callback_entry_3 ((void*)$a_feature);
			]"
		end

	c_call_int_structwiringpinodestructp_int_anonymous_callback (a_function: POINTER; node: POINTER; pin: INTEGER): INTEGER
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				return call_int_structwiringpinodestructp_int_anonymous_callback ((void*)$a_function, (struct wiringPiNodeStruct*)$node, (int)$pin);
			]"
		end

	c_set_void_structwiringpinodestructp_int_int_anonymous_callback_object (a_class: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_structwiringpinodestructp_int_int_anonymous_callback_object ((void*)$a_class);
			]"
		end

	c_set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_1 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_1 ((void*)$a_feature);
			]"
		end

	c_set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_2 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_2 ((void*)$a_feature);
			]"
		end

	c_set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_3 (a_feature: POINTER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				set_void_structwiringpinodestructp_int_int_anonymous_callback_entry_3 ((void*)$a_feature);
			]"
		end

	c_call_void_structwiringpinodestructp_int_int_anonymous_callback (a_function: POINTER; node: POINTER; pin: INTEGER; value: INTEGER)
		external
			"C inline use <ewg_eWiringPi_callback_c_glue_code.h>"
		alias
			"[
				call_void_structwiringpinodestructp_int_int_anonymous_callback ((void*)$a_function, (struct wiringPiNodeStruct*)$node, (int)$pin, (int)$value);
			]"
		end

feature -- Externals Address

end
